### ISSUE TITLE
Bulk Actions in Snippets List not working properly

### ISSUE THREAD

**Issue by amirhmoradi** [codesnippetspro/code-snippets#164] opened 2023-02-24 19:56 UTC
in snippets list, when choosing some snippets (NOT ALL), then choosing the "Activate" from the "Bulk Actions" dropdown, it will activate ALL the snippets instead of the selected ones.
This is very annoying, please advise.

**Comment by sheabunge** [comment] 2023-02-25 02:40
I just tried this out, and I'm afraid I'm unable to reproduce the problem. Would you be able to provide some screenshots or a recording showing what's happening?

**Comment by sheabunge** [comment] 2023-03-04 11:44
Closing this as invalid for now. If you're able to provide some further evidence to assist us with reproducing and debugging the problem, we'd love to work with you to fix it.

**Closed by sheabunge** 2023-03-04 11:44 UTC
